spring:
  datasource:
    url: jdbc:sqlite:main.db
    driver-class-name: org.sqlite.JDBC
  thymeleaf:
    cache: false

  servlet:
    multipart:
      max-file-size: 512MB
      max-request-size: 512MB

server:
  port: 8082