spring:
  datasource:
    url: jdbc:sqlite:C:\Users\19035\Desktop\VenueManagementSystem\main.db
    driver-class-name: org.sqlite.JDBC
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    cache: false

  servlet:
    multipart:
      max-file-size: 32MB
      max-request-size: 32MB